### ISSUE TITLE
Android nothing appear when enable

### ISSUE THREAD

**Issue by yelkamel** [sundayhd/react-native-display#1]
I have an issue on Android (it's work very well on iOS) when I tried to show the view inside the display nothing appear any ideas how I can fix it ?

**Comment by sundayhd** [comment]
Try to set `height` and `width` for both the display and the view inside the display
for example:
`<Display enable={true} style={{width: 100, height: 100}}>
<View style={{width: 100, height: 100, backgroundColor: "red"}}></View></Display>`

please let me know if that fix your problem,
if not, you can share your code here and I will try to help.

**Comment by yelkamel** [comment]
It's works thank :) 
I didn't know this difference with the View between iOS and Android
