### ISSUE TITLE
Wait for image to load

### ISSUE THREAD

**Issue by ArielS1** [sundayhd/react-native-display#2]
Hi,

I'm trying to show an of an image loaded online.
the thing is it takes a little bit to show the image, so i think that the animation takes place on a transparent image that hasn't been loaded yet, and only then it shows up.

I tried to use it like this:
`
          <Display enable={this.state.popImage}>
              <Image
                   onLoad={() => this.setState({ uri: this.state.uri, popImage: true })}
                   style={{ width: 200, height: 200 }}
                   source={{ uri: this.state.uri }}
              />
        </Display>`

but then nothing happens at all
i think it's some kind of a recursive problem
when i set the image at the first time the popImage is false, and then when i load the image it calls setState() that reset the uri and bool, but then the image is reloaded again :-)

do you have a suggestion of how to initiate the animation only after the image is fully loaded?

Thanks

**Comment by sundayhd** [comment]
Try to pass keepAlive={true} for example:
'''
<Display enable={this.state.popImage}> keepAlive={true} <Image onLoad={() => this.setState({ uri: this.state.uri, popImage: true })} style={{ width: 200, height: 200 }} source={{ uri: this.state.uri }} /> </Display>
'''

Let me know if that helps.

**Comment by ArielS1** [comment]
It now shows the image, but without animation.
i tried to show it slowly by setting enterDuration={10000}, but then i discovered that the animation doesn't work either.

i got it working after i set enter: "fadeInRight"

it seems that without the enter arg it doesn't show animation.

that leads me to point that i think the readme lacks the list of all possible animations.

How can i use the cool animation showed at the top gif of the readme?

Thanks

**Comment by sundayhd** [comment]
You right you must pass enter prop for animations to work,
For full animations list you can refer to:
https://github.com/oblador/react-native-animatable
At the bottom part you will see all the strings that you can use for enter / exit props

**Comment by sundayhd** [comment]
So.. can we close this issue?

**Comment by ArielS1** [comment]
yep, it looks ok
